[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'forge-cache'
optimizer = true
optimizer-runs = 100
via_ir = true

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

# See more config options https://github.com/foundry-rs/foundry/tree/master/config